#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
else
  export BROWSER=`which firefox`
  export USERWM=`which xmonad`
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  eval "$(locale)"
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath manpath path
typeset -gUT INFOPATH infopath

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that info searches for manuals.
infopath=(
  /usr/local/share/info
  /usr/share/info
  $infopath
)

# Set the list of directories that man searches for manuals.
manpath=(
  /usr/local/share/man
  /usr/share/man
  $manpath
)

for path_file in /etc/manpaths.d/*(.N); do
  manpath+=($(<$path_file))
done
unset path_file

# Set the list of directories that Zsh searches for programs.
path=(
  /home/mcdon/.gem/ruby/1.9.1/bin  # ruby local path
  /home/mcdon/perl5/bin # perl local path
  /usr/local/admb/bin   # admb
  /opt/matlab/bin       # matlab
  /usr/lib/rstudio/bin  # rstudio
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
  $path
)

for path_file in /etc/paths.d/*(.N); do
  path+=($(<$path_file))
done
unset path_file

#
# Temporary Files
#

if [[ -d "$TMPDIR" ]]; then
  export TMPPREFIX="${TMPDIR%/}/zsh"
  if [[ ! -d "$TMPPREFIX" ]]; then
    mkdir -p "$TMPPREFIX"
  fi
fi

#
# Environmental variables
# 

# Cabal
export ARCH_HASKELL='John McDonnell <john.v.mcdonnell@gmail.com>'

# ADMB
export ADMB_HOME=/usr/local/admb/

# Perl
export PERL_LOCAL_LIB_ROOT="/home/mcdon/perl5"
export PERL_MB_OPT="--install_base /home/mcdon/perl5"
export PERL_MM_OPT="INSTALL_BASE=/home/mcdon/perl5"
export PERL5LIB="/home/mcdon/perl5/lib/perl5/x86_64-linux-thread-multi:/home/mcdon/perl5/lib/perl5"

# Matlab
export AWT_TOOLKIT=MToolkit
export MATLAB_JAVA=/usr/lib/jvm/java-7-openjdk/jre

