#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Powerline prompt
#. /Users/mcdon/.vim/plugin/powerline/powerline/bindings/bash/powerline.sh

# fasd
eval "$(fasd --init auto)"
alias v='f -e vim -b viminfo'
alias o='f -e xdg-open'
bindkey '^X^A' fasd-complete    # C-x C-a to do fasd-complete (fils and directories)
bindkey '^X^F' fasd-complete-f  # C-x C-f to do fasd-complete-f (only files)
bindkey '^X^D' fasd-complete-d  # C-x C-d to do fasd-complete-d (only directories)

# Autojump (replaced by fasd)
#source /etc/profile.d/autojump.zsh


